### ISSUE TITLE
decode-pb-event-record decodes the time to double while encode-pb-event encodes time to long

### ISSUE THREAD

**Issue by hcheng15** [riemann/riemann-clojure-client#30]
https://github.com/riemann/riemann-clojure-client/blob/master/src/riemann/codec.clj

On line 71, inside `encode-pb-event`:

`(when (:time e) (do (.setTimeMicros event (long (* 1000000 (:time e))))
                        (.setTime       event (long (:time e)))))`

On line 40, inside `decode-pb-event-record`:
`(cond
      (.hasTimeMicros e) (/ (double (.getTimeMicros e)) 1000000) ;; time in us => s
      (.hasTime e)       (.getTime e) ;; time in s`

Assuming the two functions are inverses of each other, this means while the sender is encoding the time as long, the receiving end is decoding it as double.

I don't think correctness is affected for arithmetic operations because double should still be precise enough but it is still kind of strange and problematic when the time is turned into a string.

**Comment by mcorbin** [comment]
Indeed. You will also have double with the default condition:

```clojure
true               (/ (double (System/currentTimeMillis))
                            1000)) ;; default
```

**Comment by jamtur01** [comment]
Please re-open if you continue to have issues.
